from settings.global_settings import BROAD_CRAWL_DB_CONFIG, BROAD_CRAWL_CENTRAL_DB_CONFIG, LABS_CORE_DB_CONFIG


class MysqlDBNames:
    BROAD_CRAWL_DB = BROAD_CRAWL_DB_CONFIG['db_name']
    BROAD_CRAWL_CENTRAL_DB = BROAD_CRAWL_CENTRAL_DB_CONFIG['db_name']
    LABS_CORE_DB = LABS_CORE_DB_CONFIG['db_name']

